[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build.environment]
  NODE_VERSION = "20.14.0"
  NODE_OPTIONS = "--openssl-legacy-provider"
  VITE_SKIP_NODE_WARNING = "1"
  NPM_FLAGS = "--force"

[build]
  base = "client"
  command = "npm ci && npm run build"
  publish = "dist"