# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Optionally, you could set default values for environment variables, but these will be overridden at runtime
ENV POSTGRES_DB=defaultdb
ENV POSTGRES_USER=defaultuser
ENV POSTGRES_PASSWORD=defaultpassword

# Expose the PostgreSQL port
EXPOSE 5432
