# Use the official PostgreSQL image as the base image
FROM postgres:latest


# Optionally, you could set default values for environment variables, but these will be overridden at runtime
ENV POSTGRES_DB="minidoro"
ENV POSTGRES_USER="root"
ENV POSTGRES_PASSWORD="123123"

# Expose the PostgreSQL port
EXPOSE 5432